all: report

report: sune_debel_master_thesis.tex
	pdflatex sune_debel_master_thesis.tex; \
	bibtex sune_debel_master_thesis.aux; \
	pdflatex sune_debel_master_thesis.tex; \
	pdflatex sune_debel_master_thesis.tex
